# Generated by Django 5.1 on 2025-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('school_admin', 'School Admin')], default='student', max_length=20),
        ),
    ]
